// Pages/TermsAndConditions.jsx
import React from "react";
import { motion } from "framer-motion";

const accent = "#D4B25F";

const TermsAndConditions = () => {
  return (
    <motion.div
      className=" px-4 sm:px-8 md:px-16 lg:px-32 py-12 bg-[#FFFDF8] text-gray-900"
      initial={{ opacity: 0, y: 30 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.6 }}
    >
      <h1
        className="text-4xl font-bold text-center mb-10 font-serif"
        style={{ color: accent }}
      >
        Terms &amp; Conditions
        <br />
        <span className="mt-4 block text-base font-normal tracking-wide">
          This website is operated by Bhagwati Traders
        </span>
      </h1>

      <div className="space-y-6 text-justify leading-relaxed">
        <p>
          This document is an electronic record in terms of the Information
          Technology Act, 2000 and rules thereunder as applicable, and the
          amended provisions pertaining to electronic records in various
          statutes as amended by the Information Technology Act, 2000.
        </p>

        <p>
          This electronic record is generated by a computer system and does not
          require any physical or digital signatures.
        </p>

        <p>
          This document is published in accordance with the provisions of Rule
          3(1) of the Information Technology (Intermediaries Guidelines) Rules,
          2011 that require publishing the rules and regulations, privacy policy
          and Terms of Use for access or usage of the domain{" "}
          <a
            href="https://bhagwatitrader.co.in/"
            className="underline font-medium"
            style={{ color: accent }}
            target="_blank"
            rel="noopener noreferrer"
          >
            https://bhagwatitrader.co.in/
          </a>{" "}
          (hereinafter referred to as the “Platform”).
        </p>

        <p>
          The Platform is owned and operated by{" "}
          <strong>Bhagwati Traders</strong>, a business registered under
          applicable Indian laws, with its principal place of business at:{" "}
          <em>
            GROUND FLOOR, PLOT NO. 119-120, BLK-D-DDA, SLUM COLONY, Rohini
            Sector 24, New Delhi, North West Delhi, Delhi, 110085
          </em>{" "}
          (hereinafter referred to as the “Platform Owner,” “we,” “us,” “our”).
        </p>

        {/* 1 */}
        <h2
          className="text-2xl font-semibold mt-8"
          style={{ color: accent }}
        >
          1. Acceptance of Terms
        </h2>
        <p>
          Your use of the Platform, its services, tools, and any associated
          transactional features are governed by these Terms &amp; Conditions
          (“Terms of Use”), including all policies referenced herein (such as
          our Privacy Policy and Cookie Policy).
        </p>
        <p>
          By using, visiting, registering on, or transacting through the
          Platform, you agree to be legally bound by these Terms. If you do not
          agree, please refrain from using the Platform.
        </p>
        <p>
          Any terms proposed by you that conflict with these Terms are
          expressly rejected. We reserve the right to modify these Terms at any
          time without prior notice. It is your responsibility to review them
          periodically.
        </p>

        {/* 2 */}
        <h2
          className="text-2xl font-semibold mt-8"
          style={{ color: accent }}
        >
          2. General Terms of Use
        </h2>
        <ul className="list-disc ml-6 space-y-2 text-gray-800">
          <li>Use of the Platform implies acceptance of these Terms.</li>
          <li>
            You agree to provide true, accurate, current, and complete
            information and are responsible for all activity under your account
            or enquiry submission.
          </li>
          <li>
            While we strive for accuracy, we do not guarantee that all
            information on the Platform (product data, pricing, availability,
            certifications, etc.) is free from error. We disclaim liability for
            inaccuracies to the maximum extent allowed by law.
          </li>
          <li>
            Evaluate suitability before purchase or consumption. Use our
            products and services at your own discretion and risk.
          </li>
          <li>
            All content, branding, images, logos, data, and design elements on
            the Platform are proprietary or licensed. No rights are granted to
            you except as expressly permitted.
          </li>
          <li>
            Unauthorized reproduction, scraping, reverse engineering, or
            commercial use without written consent may result in legal action.
          </li>
          <li>
            You agree to pay all applicable charges (if any) related to orders,
            shipping, and services used on or through the Platform.
          </li>
          <li>
            You agree not to use the Platform for fraudulent, unlawful,
            defamatory, or abusive purposes.
          </li>
          <li>
            The Platform may contain links to third-party sites (payments,
            delivery tracking, social media). Use of those resources is subject
            to their respective policies; we are not responsible for their
            content or practices.
          </li>
          <li>
            By placing an order, submitting a wholesale enquiry, or engaging in
            business via the Platform, you enter into a legally binding
            arrangement with us (subject to our acceptance, stock, and
            verification).
          </li>
          <li>
            You shall indemnify and hold us harmless from claims, damages, or
            losses arising out of your misuse of the Platform or breach of these
            Terms.
          </li>
          <li>
            We are not liable for delays or failure to perform due to Force
            Majeure events (natural disaster, pandemic, supply disruption,
            transport strike, government action, etc.).
          </li>
        </ul>

        {/* 3 */}
        <h2
          className="text-2xl font-semibold mt-8"
          style={{ color: accent }}
        >
          3. Product, Ordering &amp; Use
        </h2>
        <p>
          Our Platform showcases packaged Desi Ghee in various sizes. Images are
          illustrative; packaging received may vary slightly. All product claims
          (purity, source, etc.) are based on internal process standards and
          vendor declarations unless otherwise certified.
        </p>
        <p>
          Bulk, wholesale, dealer, or institutional orders may be subject to
          additional agreements, documentation (GST, trade license), and pricing
          terms. Contact us for B2B enquiries.
        </p>

        {/* 4 */}
        <h2
          className="text-2xl font-semibold mt-8"
          style={{ color: accent }}
        >
          4. Cancellation, Refunds &amp; Returns
        </h2>
        <p>
          Food products are perishable. Returns are accepted <em>only</em> in
          cases of product damage, leakage, wrong item, or tampering proven on
          delivery (subject to policy). Please refer to our{" "}
          <a
            href="/refund-return"
            className="underline"
            style={{ color: accent }}
          >
            Refund &amp; Return Policy
          </a>{" "}
          for detailed terms.
        </p>

        {/* 5 */}
        <h2
          className="text-2xl font-semibold mt-8"
          style={{ color: accent }}
        >
          5. Governing Law &amp; Jurisdiction
        </h2>
        <p>
          These Terms shall be governed by and construed in accordance with the
          laws of India. Subject to applicable dispute resolution processes, the
          courts located in <strong>New Delhi, India</strong> shall have
          exclusive jurisdiction.
        </p>

        {/* 6 */}
        <h2
          className="text-2xl font-semibold mt-8"
          style={{ color: accent }}
        >
          6. Contact
        </h2>
        <p>
          For questions regarding these Terms, transactions, business
          partnerships, or legal notices, please contact us:
        </p>
        <div
          className="p-4 rounded-md border mt-2"
          style={{ borderColor: accent, backgroundColor: "#FFF8ED" }}
        >
          <p>
            <strong>Bhagwati Traders</strong>
          </p>
          <p>
            GROUND FLOOR, PLOT NO. 119-120, BLK-D-DDA, SLUM COLONY, Rohini
            Sector 24, New Delhi, North West Delhi, Delhi, 110085
          </p>
          <p>
            Email:{" "}
            <a
              href="mailto:Info@bhagwatitrader.co.in"
              className="underline"
              style={{ color: accent }}
            >
              Info@bhagwatitrader.co.in
            </a>
          </p>
          <p>
            Alternate Email:{" "}
            <a
              href="mailto:Bhagwatitradersdelhi1@gmail.com"
              className="underline"
              style={{ color: accent }}
            >
              Bhagwatitradersdelhi1@gmail.com
            </a>
          </p>
          <p>
            Phone:{" "}
            <a
              href="tel:+917303672909"
              className="underline"
              style={{ color: accent }}
            >
              +91 7303672909
            </a>
          </p>
        </div>

        {/* Regulatory IDs */}
        <div className="mt-8 text-sm text-gray-700">
          <p>
            <strong style={{ color: accent }}>GSTIN:</strong> 07GKXPS5124N1Z3
          </p>
          <p>
            <strong style={{ color: accent }}>UDYAM:</strong> UDYAM-DL-06-0166578
          </p>
        </div>

        {/* Last Updated */}
        <p className="mt-10 text-xs text-gray-500 text-center">
          Last Updated:{" "}
          {new Date().toLocaleDateString("en-IN", {
            day: "2-digit",
            month: "short",
            year: "numeric",
          })}
        </p>
      </div>
    </motion.div>
  );
};

export default TermsAndConditions;
