// Pages/TermsAndConditions.jsx
import React from "react";
import { motion } from "framer-motion";

/* -------------------------------------------------
   Brand & Contact Constants
-------------------------------------------------- */
const BRAND_GOLD = "#F4B400";
const BRAND_MAROON = "#7A1E09";

const CONTACT_PHONE_DISPLAY = "+91 9211841929";
const CONTACT_PHONE_RAW = "919211841929";
const CONTACT_EMAIL_PRIMARY = "Info@shivtrader.co.in";
const CONTACT_EMAIL_SECONDARY = "Shivtradersdelhi1@gmail.com";

const CONTACT_ADDRESS_LINES = [
  "Flat No. 15, 3rd Floor",
  "Block A-4, Pocket 1",
  "Rohini Sector 34",
  "North West Delhi, 110042",
  "India",
];

const GSTIN = "07MHBPK0355G1ZE";
const UDYAM = "##############"; // update when available

/* -------------------------------------------------
   Section Heading Helper
-------------------------------------------------- */
const SectionHeading = ({ children }) => (
  <h2
    className="text-2xl font-semibold mt-10 mb-3 leading-snug font-heading"
    style={{ color: BRAND_MAROON, fontFamily: "Merriweather, serif" }}
  >
    {children}
  </h2>
);

/* -------------------------------------------------
   Terms & Conditions Component
-------------------------------------------------- */
const TermsAndConditions = () => {
  const lastUpdated = new Date().toLocaleDateString("en-IN", {
    day: "2-digit",
    month: "short",
    year: "numeric",
  });

  return (
    <motion.div
      className="px-4 sm:px-8 md:px-16 lg:px-32 py-12 bg-[#FDF8F3] text-gray-900 font-sans pt-32"
      initial={{ opacity: 0, y: 30 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.8, ease: "easeOut" }}
    >
      <div className="max-w-5xl mx-auto bg-white/95 backdrop-blur-lg rounded-2xl shadow-xl p-8 md:p-12 border border-[#f5f0e8]">
        {/* Title */}
        <h1
          className="text-4xl md:text-5xl font-extrabold text-center mb-3 font-heading tracking-wide"
          style={{
            background: `linear-gradient(90deg,${BRAND_GOLD},#C47E00)`,
            WebkitBackgroundClip: "text",
            WebkitTextFillColor: "transparent",
            fontFamily: "Merriweather, serif",
          }}
        >
          Terms &amp; Conditions
        </h1>
        <span className="block text-center text-base font-normal tracking-wide text-gray-600 mb-10">
          This website is operated by <strong>Shiv Traders</strong>
        </span>

        {/* Electronic Record Notice */}
        <section className="space-y-6 text-justify leading-relaxed">
          <p>
            This document is an electronic record in terms of the Information Technology Act,
            2000 and rules made thereunder, and the amended provisions pertaining to electronic
            records in various statutes as amended by the Information Technology Act, 2000.
          </p>
          <p>
            This electronic record is generated by a computer system and does not require any
            physical or digital signatures.
          </p>
          <p>
            This document is published in accordance with Rule 3(1) of the Information Technology
            (Intermediaries Guidelines) Rules, 2011, which require publishing the rules and
            regulations, privacy policy, and terms of use for access or usage of this website
            (the “Platform”).
          </p>
          <p>
            The Platform is owned and operated by <strong>Shiv Traders</strong>, a business
            registered under applicable Indian laws, with its principal place of business at:
            <em> Flat No. 15, 3rd Floor, Block A-4, Pocket 1, Rohini Sector 34, North West Delhi,
            110042, India</em> (hereinafter referred to as “we,” “us,” “our,” or the “Platform Owner”).
          </p>
        </section>

        {/* 1. Acceptance */}
        <SectionHeading>1. Acceptance of Terms</SectionHeading>
        <p>
          Your use of the Platform, its content, services, enquiry tools, purchase flows, and
          communication features are governed by these Terms &amp; Conditions (“Terms”), including
          policies referenced herein such as our{" "}
          <a href="/privacy-policy" className="underline" style={{ color: BRAND_GOLD }}>
            Privacy Policy
          </a>{" "}
          and{" "}
          <a href="/cookie-policy" className="underline" style={{ color: BRAND_GOLD }}>
            Cookie Policy
          </a>
          .
        </p>
        <p>
          By accessing, browsing, submitting an enquiry, or placing an order through the Platform,
          you acknowledge that you have read, understood, and agree to be bound by these Terms. If
          you do not agree, please discontinue use immediately.
        </p>
        <p>
          We may revise these Terms at any time. Updates will be posted here and become effective
          upon posting. Continued use after changes constitutes acceptance.
        </p>

        {/* 2. General Use */}
        <SectionHeading>2. General Terms of Use</SectionHeading>
        <ul className="list-disc ml-6 space-y-2 text-gray-800">
          <li>Using the Platform implies acceptance of these Terms.</li>
          <li>
            You agree to provide accurate contact, address, and business details and are responsible
            for all activity performed under your submissions or account (if any).
          </li>
          <li>
            We strive to maintain accurate product, pack size, and pricing info; however,
            typographical, listing, or inventory errors may occur. We reserve the right to correct
            errors and cancel or adjust orders.
          </li>
          <li>
            Evaluate suitability before purchase or consumption. Nutrition tolerance, dietary needs,
            and usage conditions vary by individual; use at your discretion.
          </li>
          <li>
            All content (text, graphics, photos, logo, pack imagery, UI design) is proprietary or
            licensed. No reproduction, resale, or scraping without written permission.
          </li>
          <li>
            You may not misuse the Platform: no fraud, harmful code, harassment, defamation,
            impersonation, or unlawful activity.
          </li>
          <li>
            By submitting an order or wholesale enquiry, you authorize us to contact you via phone,
            email, SMS, or WhatsApp regarding that request.
          </li>
          <li>
            Charges for products, shipping, taxes, and services (if applicable) must be paid in full
            per invoice unless alternate credit terms are agreed in writing.
          </li>
          <li>
            The Platform may contain third‑party links (payments, courier tracking, social media).
            Their policies apply separately; we are not responsible for third‑party content.
          </li>
          <li>
            You agree to indemnify and hold us harmless from claims arising out of misuse, fraud,
            violation of law, or breach of these Terms.
          </li>
          <li>
            We are not liable for delays or service failures caused by Force Majeure events (natural
            disasters, extreme weather, transport strikes, lockdowns, supply chain disruptions,
            government restrictions, etc.).
          </li>
        </ul>

        {/* 3. Products & Orders */}
        <SectionHeading>3. Products, Representation &amp; Ordering</SectionHeading>
        <p>
          The Platform lists packaged Desi Ghee in multiple consumer and bulk sizes. Images shown
          are for illustration; label, jar/tin shape, or packaging details may vary by batch.
        </p>
        <p>
          All specifications (fat %, aroma notes, source info) are based on internal production
          processes, supplier data, or lab checks where applicable. Variations in color or granule
          texture are natural in traditional ghee.
        </p>
        <p>
          Wholesale, dealership, or institutional supply orders may require additional documentation
          (GST, FSSAI license, trade credentials) and may follow a separate supply agreement.
        </p>

        {/* 4. Pricing, Payment & Taxes */}
        <SectionHeading>4. Pricing, Payment &amp; Taxes</SectionHeading>
        <p>
          Prices shown are in INR unless noted. Taxes (GST) apply per item class. Shipping is
          calculated at checkout or via quote for bulk orders. We reserve the right to update
          prices without prior notice. Promotional pricing may be time‑bound.
        </p>
        <p>
          Payment methods may include UPI, net banking, cards, or offline bank transfer (for bulk).
          Orders are processed after payment confirmation unless credit terms are agreed.
        </p>

        {/* 5. Shipping */}
        <SectionHeading>5. Shipping &amp; Delivery</SectionHeading>
        <p>
          We ship across most Indian pin codes. Delivery timelines vary by region. See our{" "}
          <a href="/shipping-policy" className="underline" style={{ color: BRAND_GOLD }}>
            Shipping Policy
          </a>{" "}
          for details on processing time, transit estimates, and tracking.
        </p>

        {/* 6. Cancellations & Returns */}
        <SectionHeading>6. Cancellations, Returns &amp; Refunds</SectionHeading>
        <p>
          Food products are perishable. Returns are accepted only under defined criteria such as
          transit damage, wrong item, or sealed product return within the allowed window. Review our{" "}
          <a href="/refund-return" className="underline" style={{ color: BRAND_GOLD }}>
            Refund &amp; Return Policy
          </a>{" "}
          before submitting a claim.
        </p>

        {/* 7. User Communications */}
        <SectionHeading>7. Communications &amp; Notifications</SectionHeading>
        <p>
          By providing contact information, you consent to receive transactional updates (order,
          shipping, support) and limited promotional messages. You may opt out of marketing at any
          time via provided unsubscribe instructions or by contacting us.
        </p>

        {/* 8. Intellectual Property */}
        <SectionHeading>8. Intellectual Property &amp; Licensing</SectionHeading>
        <p>
          All trademarks, branding, product photographs, packaging artwork, website copy, and layout
          are intellectual property of Shiv Traders or its licensors. Use, reproduction, distribution,
          or derivative design without written permission is prohibited.
        </p>

        {/* 9. Limitation of Liability */}
        <SectionHeading>9. Limitation of Liability</SectionHeading>
        <p>
          To the fullest extent permitted by law, Shiv Traders shall not be liable for indirect,
          incidental, punitive, consequential, or special damages arising from use of the Platform,
          delays in delivery, or product use beyond our control. Total liability, if established,
          shall not exceed the amount paid for the affected order.
        </p>

        {/* 10. Governing Law */}
        <SectionHeading>10. Governing Law &amp; Jurisdiction</SectionHeading>
        <p>
          These Terms are governed by the laws of India. Subject to applicable dispute resolution
          procedures, courts located in <strong>New Delhi, India</strong> shall have exclusive
          jurisdiction.
        </p>

        {/* 11. Contact */}
        <SectionHeading>11. Contact Information</SectionHeading>
        <p>
          For questions regarding these Terms, business partnerships, legal notices, or escalations,
          please reach out:
        </p>
        <div
          className="p-6 rounded-md border mt-2 mb-6"
          style={{ borderColor: BRAND_GOLD, backgroundColor: "#FFF8E7" }}
        >
          <p className="font-semibold" style={{ color: BRAND_MAROON }}>
            Shiv Traders
          </p>
          <address className="not-italic leading-relaxed text-gray-800 mt-1 mb-4">
            {CONTACT_ADDRESS_LINES.map((l) => (
              <span key={l} className="block">
                {l}
              </span>
            ))}
          </address>
          <p>
            Email:{" "}
            <a
              href={`mailto:${CONTACT_EMAIL_PRIMARY}`}
              className="underline break-all"
              style={{ color: BRAND_GOLD }}
            >
              {CONTACT_EMAIL_PRIMARY}
            </a>
          </p>
          <p>
            Alternate Email:{" "}
            <a
              href={`mailto:${CONTACT_EMAIL_SECONDARY}`}
              className="underline break-all"
              style={{ color: BRAND_GOLD }}
            >
              {CONTACT_EMAIL_SECONDARY}
            </a>
          </p>
          <p className="mt-2">
            Phone:{" "}
            <a
              href={`tel:+${CONTACT_PHONE_RAW}`}
              className="underline"
              style={{ color: BRAND_GOLD }}
            >
              {CONTACT_PHONE_DISPLAY}
            </a>
          </p>
        </div>

        {/* Regulatory IDs */}
        <div className="mt-8 text-sm text-gray-700">
          <p>
            <strong style={{ color: BRAND_GOLD }}>GSTIN:</strong> {GSTIN}
          </p>
        </div>

        {/* Last Updated */}
        <p className="mt-10 text-xs text-gray-500 text-center">
          Last Updated: {lastUpdated}
        </p>
      </div>
    </motion.div>
  );
};

export default TermsAndConditions;
